server:
  port: 8000

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8001
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: http://user-service:8002
          predicates:
            - Path=/users/**
  data:
    redis:
      host: redis
      port: 6379 